### ISSUE TITLE
Upload 0.3.0 to Hackage

### ISSUE THREAD

**Issue by haphut** [k00mi/mqtt-hs#1]
Hey!

If you think the package is ready for 0.3.0, would you kindly upload it to Hackage? Thanks.

**Comment by k00mi** [comment]
I'll upload a new version in the next few days if no problems come up. It'll be 1.0 because the API changed quite drastically.

**Comment by haphut** [comment]
Excellent. Thanks for your efforts.

**Comment by k00mi** [comment]
New version is on [hackage](https://hackage.haskell.org/package/mqtt-hs-1.0.0). Docs are still building, might be I'll have to upload them myself later.
