### ISSUE TITLE
Persistent connections, data received before handler setup

### ISSUE THREAD

**Issue by gpampara** [k00mi/mqtt-hs#5]
It seems that the library receives queued messages from the MQTT broker (when the clientId is defined and the session is marked as _not_ clean), but the messages are received before the handler seems to be ready, so that messages can be consumed and not lost.

I did a test where the broker was set up to persist these messages, then I published 4 messages followed by starting my haskell app, using mqtt-hs. The logging in the library resulted in this trace:

```
[Debug] Received PUBLISH
[Debug] Sending PUBACK
[Debug] Received PUBLISH
[Debug] Received PUBLISH
[Debug] Sending PUBACK
[Debug] Received PUBLISH
[Debug] Sending PUBACK
[Debug] Received SUBACK
[Debug] Sending PUBACK
Subscribed with QoS: Confirm
```

The message "Subscribed with QoS" is some output from my application, which happens after the call to `subscribe mqtt Confirm <topic>`

It would therefore seem that those 4 messages are lost?

**Comment by gpampara** [comment]
I just tested commit 4184ddf5e3df38d4a9ced20a8d271127d54d0ce2 and it works really well for me right now. :+1:

**Comment by k00mi** [comment]
Good to hear. I haven't tested it much myself yet but I'll merge it and make a hackage release with the new API eventually.
