### ISSUE TITLE
Better handing of broker closing after subscriber callback

### ISSUE THREAD

**Issue by carlosayam** [k00mi/mqtt-hs#7]
I tried mqtt-hs (0.3.0) with mosquitto and it seems this broker was closing the connection too soon (?). I am not sure, but my few attempts can be found in stackoverflow, here

http://stackoverflow.com/questions/36743322/basic-mqtt-with-haskell

**Comment by k00mi** [comment]
I'm not sure what's going wrong here.

I rewrote a lot of the internals and suspect the problem went away with that, so I'll close this for now. Please reopen if it still happens for you.
